version: "3.9"

services:
  backend:
    build: ./full-stack-job-portal-server-main
    container_name: job-portal-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./full-stack-job-portal-client-main
    container_name: job-portal-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

